import Head from 'next/head'
import { Inter } from '@next/font/google'
import Cartao from '../components/Cartao'
import styles from "../styles/Formulario.module.css"
import Link from 'next/link'
import EntradaNumerica from '../components/EntradaNumerica'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Formulario() {
  const [qtdPortas, setQtdPortas] = useState(3)
  const [comPresente, setComPresente] = useState(1)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.formulario}>
        <div>
          <Cartao bgcolor="#c0392c">
            <h1>Monty Hall</h1>
          </Cartao>
          <Cartao>
            <EntradaNumerica text="Qtd portas?" 
              value={qtdPortas} 
              onChange={novaQtd => setQtdPortas(novaQtd)} />
          </Cartao>
        </div>
        <div>
          <Cartao>
            <EntradaNumerica text='Porta com presente?'
              value={comPresente}
              onChange={novaPortaComPresente => setComPresente(novaPortaComPresente)} />
          </Cartao>
          <Cartao bgcolor="#28a085">
            <Link href={`/jogo/${qtdPortas}/${comPresente}`}>
              <h2 className={styles.link}>Iniciar</h2>
            </Link>
          </Cartao>
        </div>
      </main>
    </>
  )
}
